include:
  - compose.db.yaml

services:
  next-app-dev:
    build:
      context: ./next-app
      dockerfile: ../Dockerfile
      target: builder
    env_file:
      - ./.env
    volumes:
      - ./next-app:/app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
        required: true